<a href="https://colab.research.google.com/github/tnmanju/fundamental-ngx/blob/master/M2_NB_MiniProject_2_Linear_Algebra_and_Calculus_manju.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Advanced Certification Program in Computational Data Science
## A program by IISc and TalentSprint
### Mini Project Notebook: Linear Algebra and Calculus

## Problem Statement

 The task is to advise a petroleum company on how to meet the demands of their customers for motor oil, diesel oil and gasoline.

## Learning Objectives

At the end of the experiment, you will be able to

* create arrays and matrices in python
* understand the concepts of linear equations
* solve the system of linear equations

### Data

From a barrel of crude oil, in one day, factory $A$ can produce
* 20 gallons of motor oil,
* 10 gallons of diesel oil, and
* 5 gallons of gasoline

Similarly, factory $B$ can produce
* 4 gallons of motor oil,
* 14 gallons of diesel oil, and
* 5 gallons of gasoline

while factory $C$ can produce
* 4 gallons of motor oil,
* 5 gallons of diesel oil, and
* 12 gallons of gasoline

There is also waste in the form of paraffin, among other things. Factory $A$ has 3 gallons of paraffin to dispose of per barrel of crude, factory $B$ 5 gallons, and factory $C$ 2 gallons.

**Note:** Your conclusion should include a discussion of the nature of the terms *unique*, *no solution*, *overdetermined* and *underdetermined* as they apply in the context of the oil plants.

## Grading = 10 Points

In [3]:
import numpy as np

### Create an array

Create an array of size 2x3 with arbitrary values.

In [4]:
# YOUR CODE HERE

a = np.array([[1,2,3],[4,5,6]])
print(a)

[[1 2 3]
 [4 5 6]]


### Create the system of Linear Equations

Suppose the current daily demand from distributors is 6600 gallons of motor oil, 5100 gallons of diesel oil and 3100 of gasoline.

Set up the system of equations which describes the above situation. Please include the units as well.

Let the number of barrels used by factory $A$, $B$ and $C$ are $x$, $y$ and $z$ respectively.

Then the system of linear equations will be

$$Motor\ oil:\ \ \ 20x + 4y + 4z = 6600$$

$$Diesel\ oil:\ \ \ 10x + 14y + 5z = 5100$$

$$Gasoline:\ \ \ 5x + 5y + 12z = 3100$$

### Solve the system of Linear Equation (2 points)

How many barrels of crude oil each plant should get in order to meet the demand as a group. Remember that we can only provide each plant with an integral number of barrels.

In [ ]:
# YOUR CODE HERE

# Create the augmented matrix
A = np.array([[20, 4, 4], [10, 14, 5], [5, 5, 12]])
b = np.array([6600, 5100, 3100])


Ab = np.hstack((A, b.reshape(-1, 1)))
print(A.shape)
print(f"A: {A}")
print(F"b: {b}")
print(f"Ab: {Ab}")

# Perform Gaussian elimination
for i in range(A.shape[0]):
    # Normalize the current row
    print(f"Ab[i]: {Ab[i]}")
    print(f"Ab[i][i]: {Ab[i][i]}")
    Ab[i] = Ab[i] / Ab[i][i]

    # Subtract multiples of the current row from the other rows
    for j in range(A.shape[0]):
        if i != j:
            Ab[j] -= Ab[j][i] * Ab[i]

print(f"Ab: {Ab}")
# Extract the solution
x = Ab[:, -1]

# Print the solution
print("The number of barrels of crude oil each plant should get is:")
print(x)

# The number of barrels of crude oil each plant should get is:
# [200. 150. 100.]

(3, 3)
A: [[20  4  4]
 [10 14  5]
 [ 5  5 12]]
b: [6600 5100 3100]
Ab: [[  20    4    4 6600]
 [  10   14    5 5100]
 [   5    5   12 3100]]
Ab[i]: [  20    4    4 6600]
Ab[i][i]: 20
Ab[i]: [   0   14    5 1800]
Ab[i][i]: 14
Ab[i]: [  0   0  12 810]
Ab[i][i]: 12
Ab: [[  1   0   0 330]
 [  0   1   0 128]
 [  0   0   1  67]]
The number of barrels of crude oil each plant should get is:
[330 128  67]


Suppose the total demand for all products **doubled**. What would the solution now be? How does it compare to the original solution? Why, mathematically, should this have been expected?

In [5]:
# Create the augmented matrix
# Coefficients matrix A
A = np.array([[20, 4, 4], [10, 14, 5], [5, 5, 12]])

# Constants vector b
b = np.array([6600, 5100, 3100])

xyz = np.linalg.solve(A, b)
print("x, y, z without rounding off: " , xyz)

int_xyz = np.round(xyz).astype(int)
print("x, y,z after rounding off: ", int_xyz)

print(f"The number of barrels of crude oil plant A should get is: {int_xyz[0]}")
print(f"The number of barrels of crude oil plant B should get is: {int_xyz[1]}")
print(f"The number of barrels of crude oil plant C should get is: {int_xyz[2]}")

x, y, z without rounding off:  [287.25 128.75  85.  ]
x, y,z after rounding off:  [287 129  85]
The number of barrels of crude oil plant A should get is: 287
The number of barrels of crude oil plant B should get is: 129
The number of barrels of crude oil plant C should get is: 85


In [6]:
# YOUR CODE HERE
# Create the augmented matrix
A = np.array([[20, 4, 4], [10, 14, 5], [5, 5, 12]])
b = np.array([6600, 5100, 3100])*2
# b = np.array([13200, 10200, 6200])

print(b)

# xyz = np.linalg.solve(A, b)
int_xyz = np.linalg.solve(A, b).round().astype(int)
# int_xyz = np.round(xyz).astype(int)
print("x, y,z after rounding off: ", int_xyz)

print("To meet the doubled demand of the products:")
print(f"The number of barrels of crude oil plant A should get is: {int_xyz[0]}")
print(f"The number of barrels of crude oil plant B should get is: {int_xyz[1]}")
print(f"The number of barrels of crude oil plant C should get is: {int_xyz[2]}")


[13200 10200  6200]
x, y,z after rounding off:  [574 258 170]
To meet the doubled demand of the products:
The number of barrels of crude oil plant A should get is: 574
The number of barrels of crude oil plant B should get is: 258
The number of barrels of crude oil plant C should get is: 170


Suppose that the company acquires another group of distributors and that the daily demand of this group is 2000 gallons of motor oil, 4000 gallons of gasoline, and 4000 gallons of diesel oil. How would you set up production of just this supply? Are there any options (more than one way)?

In [7]:
A = np.array([[20, 4, 4], [10, 14, 5], [5, 5, 12]])
b = np.array([2000, 4000, 4000])

int_xyz = np.linalg.solve(A, b).round().astype(int)
# int_xyz = np.round(xyz).astype(int)
print("x, y,z after rounding off: ", int_xyz)

print("To meet the new distributors demand:")
print(f"The number of barrels of crude oil plant A should get is: {int_xyz[0]}")
print(f"The number of barrels of crude oil plant B should get is: {int_xyz[1]}")
print(f"The number of barrels of crude oil plant C should get is: {int_xyz[2]}")

x, y,z after rounding off:  [ 12 188 250]
To meet the new distributors demand:
The number of barrels of crude oil plant A should get is: 12
The number of barrels of crude oil plant B should get is: 188
The number of barrels of crude oil plant C should get is: 250


In [8]:
# YOUR CODE HERE
A = np.array([[20, 4, 4], [10, 14, 5], [5, 5, 12]])
b = np.array([6600+2000, 5100+4000, 3100+4000])

int_xyz = np.linalg.solve(A, b).round().astype(int)
# int_xyz = np.round(xyz).astype(int)
print("x, y,z after rounding off: ", int_xyz)

print("To meet the total distributors demand:")
print(f"The number of barrels of crude oil plant A should get is: {int_xyz[0]}")
print(f"The number of barrels of crude oil plant B should get is: {int_xyz[1]}")
print(f"The number of barrels of crude oil plant C should get is: {int_xyz[2]}")


x, y,z after rounding off:  [300 316 335]
To meet the total distributors demand:
The number of barrels of crude oil plant A should get is: 300
The number of barrels of crude oil plant B should get is: 316
The number of barrels of crude oil plant C should get is: 335


Next, calculate the needs of each factory (in barrels of crude, as usual) to meet the total demand of both groups of distributors. When you have done this, compare your answer to results already obtained. What mathematical conclusion can you draw?

Percentage increase in barrels of crude oil for A, B and C are as follows:
A = 4.52 %
B = 144.96 %
C = 294.11%

Diesel and Gasoline demand has sharply increased...almost doubled. Based on the original capacity of Diesel and Gasoline production of B and C, there is sharp increase required in supply of crude oil to B and C.

In [ ]:
# YOUR CODE HERE
A = 4.52 %
B = 144.96 %
C = 294.11%


### Sensitivity and Robustness (1 point)

In real life applications, constants are rarely ever exactly equal to their stated value; certain amounts of uncertainty are always present. This is part of the reason for the science of statistics. In the above model, the daily productions for the plants would be averages over a period of time. Explore what effect small changes in the parameters have on the output.

To do this, pick any 3 coefficients, one at a time, and increase or decrease them by 3%. For each case , note what effect this has on the solution, as a percentage change. Can you draw any overall conclusion?

In [10]:
# YOUR CODE HERE
#increase by 3%, consider increase in motoroil co-efficient
A = np.array([[20+20*0.03, 4, 4], [10+10*0.03, 14, 5], [5+5*0.03, 5, 12]])
b = np.array([6600, 5100, 3100])
print(A)
int_xyz = np.linalg.solve(A, b).round().astype(int)
# int_xyz = np.round(xyz).astype(int)
print("x, y,z after rounding off: ", int_xyz)

print("Considering 3% increase in x co-efficient(Plant A):")
print(f"The number of barrels of crude oil plant A should get is: {int_xyz[0]}")
print(f"The number of barrels of crude oil plant B should get is: {int_xyz[1]}")
print(f"The number of barrels of crude oil plant C should get is: {int_xyz[2]}")


[[20.6   4.    4.  ]
 [10.3  14.    5.  ]
 [ 5.15  5.   12.  ]]
x, y,z after rounding off:  [279 129  85]
Considering 3% increase in x co-efficient(Plant A):
The number of barrels of crude oil plant A should get is: 279
The number of barrels of crude oil plant B should get is: 129
The number of barrels of crude oil plant C should get is: 85


𝑀𝑜𝑡𝑜𝑟 𝑜𝑖𝑙: 20𝑥+4𝑦+4𝑧=6600

𝐷𝑖𝑒𝑠𝑒𝑙 𝑜𝑖𝑙: 10𝑥+14𝑦+5𝑧=5100

𝐺𝑎𝑠𝑜𝑙𝑖𝑛𝑒: 5𝑥+5𝑦+12𝑧=3100

with 3% increase in motor oil co-efficient, there is slight **DECREASE** in crude oil consumption at A, but other two plants crude oil consumption is unchanged. This makes sense, because 1) facility A is produces more motor oil than B and C. 2) Its only facility A which has INCREASED its production efficiency of motor oil by 3%.

In [12]:
# Decrease by3%,consider decrease in motoroil co-efficient
A = np.array([[20-20*0.03, 4, 4], [10-10*0.03, 14, 5], [5-5*0.03, 5, 12]])
b = np.array([6600, 5100, 3100])
print(A)
int_xyz = np.linalg.solve(A, b).round().astype(int)
# int_xyz = np.round(xyz).astype(int)
print("x, y,z after rounding off: ", int_xyz)

print("Considering 3% decrease in x co-efficient(Plant A):")
print(f"The number of barrels of crude oil plant A should get is: {int_xyz[0]}")
print(f"The number of barrels of crude oil plant B should get is: {int_xyz[1]}")
print(f"The number of barrels of crude oil plant C should get is: {int_xyz[2]}")

[[19.4   4.    4.  ]
 [ 9.7  14.    5.  ]
 [ 4.85  5.   12.  ]]
x, y,z after rounding off:  [296 129  85]
Considering 3% decrease in x co-efficient(Plant A):
The number of barrels of crude oil plant A should get is: 296
The number of barrels of crude oil plant B should get is: 129
The number of barrels of crude oil plant C should get is: 85


with 3% decrease in motor oil co-efficient, there is slight **INCREASE** in crude oil consumption at A, but other two plants crude oil consumption is unchanged. This makes sense, because 1) facility A is produces more motor oil than B and C. 2) Its only facility A which has DECREASED its production efficiency of motor oil by 3%.

𝑀𝑜𝑡𝑜𝑟 𝑜𝑖𝑙:   20𝑥+4𝑦+4𝑧=6600

𝐷𝑖𝑒𝑠𝑒𝑙 𝑜𝑖𝑙:   10𝑥+14𝑦+5𝑧=5100

𝐺𝑎𝑠𝑜𝑙𝑖𝑛𝑒:   5𝑥+5𝑦+12𝑧=3100

In [14]:
#increase by 3%, consider increase in diesel co-efficient
A = np.array([[20, 4+4*.03, 4], [10, 14+14*.03, 5], [5, 5+5*.03, 12]])
b = np.array([6600, 5100, 3100])
print(A)
int_xyz = np.linalg.solve(A, b).round().astype(int)
# int_xyz = np.round(xyz).astype(int)
print("x, y,z after rounding off: ", int_xyz)

print("Considering 3% increase in y co-efficient(diesel):")
print(f"The number of barrels of crude oil plant A should get is: {int_xyz[0]}")
print(f"The number of barrels of crude oil plant B should get is: {int_xyz[1]}")
print(f"The number of barrels of crude oil plant C should get is: {int_xyz[2]}")


[[20.    4.12  4.  ]
 [10.   14.42  5.  ]
 [ 5.    5.15 12.  ]]
x, y,z after rounding off:  [287 125  85]
Considering 3% increase in y co-efficient(diesel):
The number of barrels of crude oil plant A should get is: 287
The number of barrels of crude oil plant B should get is: 125
The number of barrels of crude oil plant C should get is: 85


Similar observation found.
Due to 3% increase in diesel production efficiency, there is **slight DECREASE** in crude oil required for facility B, which is major diesel producing facility.

In [34]:
#increase by 3%, consider decrease in diesel co-efficient
A = np.array([[20, 4-4*.03, 4], [10, 14-14*.03, 5], [5, 5-5*.03, 12]])
b = np.array([6600, 5100, 3100])
print(A)
int_xyz = np.linalg.solve(A, b).round().astype(int)
# int_xyz = np.round(xyz).astype(int)
print("x, y after rounding off: ", int_xyz)

print("Considering 3% decrease in y co-efficient(diesel):")
print(f"The number of barrels of crude oil plant A should get is: {int_xyz[0]}")
print(f"The number of barrels of crude oil plant B should get is: {int_xyz[1]}")
print(f"The number of barrels of crude oil plant C should get is: {int_xyz[2]}")

[[20.    3.88  4.  ]
 [10.   13.58  5.  ]
 [ 5.    4.85 12.  ]]
x, y after rounding off:  [287 133  85]
Considering 3% decrease in y co-efficient(diesel):
The number of barrels of crude oil plant A should get is: 287
The number of barrels of crude oil plant B should get is: 133
The number of barrels of crude oil plant C should get is: 85


Similar observation found. Due to 3% decrease in diesel production efficiency, there is **slight INCREASE** in crude oil required for facility B, which is major diesel producing facility.

### A Plant Off-Line (1 point)

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Suppose factory $C$ is shut down by the EPA (Environmental Protection Agency) temporarily for excessive emissions into the atmosphere. If your demand is as it was originally (6600, 5100, 3100), what would you now say about the companies ability to meet it? What do you recommend they schedule for production now?

**Option1**

In [33]:
# YOUR CODE HERE
#factory C is shoutdown. Remove its co-efficients
# We now have 20x+4y = 6600 10x+14y = 5100 5x+5y = 3100
#python program to solve: 20x+4y = 6600 10x+14y = 5100 5x+5y = 3100

# Create the augmented matrix
A = np.array([[20, 4], [10, 14]])
# A = np.array([[20, 4, 4], [10, 14, 5], [0, 0, 0]])
b = np.array([6600, 5100])

int_xyz = np.linalg.solve(A, b).round().astype(int)
# int_xyz = np.round(xyz).astype(int)
print("x, y after rounding off: ", int_xyz)

print(f"The number of barrels of crude oil plant A should get is: {int_xyz[0]}")
print(f"The number of barrels of crude oil plant B should get is: {int_xyz[1]}")

motoroil_output = 20*int_xyz[0] + 4*int_xyz[1]
dieseloil_output = 10*int_xyz[0] + 14*int_xyz[1]
gasoline_output = 5*int_xyz[0] + 5*int_xyz[1]
print(f"Motor oil production(in gallons) is: {motoroil_output}")
print(f"Diesel oil production(in gallons) is: {dieseloil_output}")
print(f"Gasoline production(in gallons) is: {gasoline_output}")

x, y after rounding off:  [300 150]
The number of barrels of crude oil plant A should get is: 300
The number of barrels of crude oil plant B should get is: 150
Motor oil production(in gallons) is: 6600
Diesel oil production(in gallons) is: 5100
Gasoline production(in gallons) is: 2250


**Conclusion:** Motor oil and Diesel oil production is met completely.
Gasoline demand(3100 gallons) is met by 72.58%.

**Option2**

In [32]:
#factory C is shoutdown. Remove its co-efficients
# We now have 20x+4y = 6600 10x+14y = 5100 5x+5y = 3100
#python program to solve: 20x+4y = 6600 10x+14y = 5100 5x+5y = 3100

# Create the augmented matrix
A = np.array([[20, 4], [5, 5]])
# A = np.array([[20, 4, 4], [10, 14, 5], [0, 0, 0]])
b = np.array([6600, 3100])

int_xyz = np.linalg.solve(A, b).round().astype(int)
# int_xyz = np.round(xyz).astype(int)
print("x, y after rounding off: ", int_xyz)


print(f"The number of barrels of crude oil plant A should get is: {int_xyz[0]}")
print(f"The number of barrels of crude oil plant B should get is: {int_xyz[1]}")

motoroil_output = 20*int_xyz[0] + 4*int_xyz[1]
dieseloil_output = 10*int_xyz[0] + 14*int_xyz[1]
gasoline_output = 5*int_xyz[0] + 5*int_xyz[1]
print(f"Motor oil production(in gallons) is: {motoroil_output}")
print(f"Diesel oil production(in gallons) is: {dieseloil_output}")
print(f"Gasoline production(in gallons) is: {gasoline_output}")

x, y after rounding off:  [258 362]
The number of barrels of crude oil plant A should get is: 258
The number of barrels of crude oil plant B should get is: 362
Motor oil production(in gallons) is: 6608
Diesel oil production(in gallons) is: 7648
Gasoline production(in gallons) is: 3100


**Conclusion**:
Motor oil demand is slightly over shot(by 0.12%).
Diesel and Diesel oil production is over shot by nearly 50%).
Gasoline demand 100% met.
Overall, Diesel oil production is shot up by 50% and this has its own storage and other costs.

Option3

In [28]:
#factory C is shoutdown. Remove its co-efficients
# We now have 20x+4y = 6600 10x+14y = 5100 5x+5y = 3100
#python program to solve: 20x+4y = 6600 10x+14y = 5100 5x+5y = 3100

# Create the augmented matrix
A = np.array([[10, 14], [5, 5]])
# A = np.array([[20, 4, 4], [10, 14, 5], [0, 0, 0]])
b = np.array([5100, 3100])

int_xyz = np.linalg.solve(A, b).round().astype(int)
# int_xyz = np.round(xyz).astype(int)
print("x, y,z after rounding off: ", int_xyz)


print(f"The number of barrels of crude oil plant A should get is: {int_xyz[0]}")
print(f"The number of barrels of crude oil plant B should get is: {int_xyz[1]}")

motoroil_output = 20*int_xyz[0] + 4*int_xyz[1]
dieseloil_output = 10*int_xyz[0] + 14*int_xyz[1]
gasoline_output = 5*int_xyz[0] + 5*int_xyz[1]
print(f"Motor oil production(in gallons) is: {motoroil_output}")
print(f"Diesel oil production(in gallons) is: {dieseloil_output}")
print(f"Gasoline production(in gallons) is: {gasoline_output}")

x, y,z after rounding off:  [ 895 -275]
The number of barrels of crude oil plant A should get is: 895
The number of barrels of crude oil plant B should get is: -275
Motor oil production(in gallons) is: 16800
Diesel oil production(in gallons) is: 5100
Gasoline production(in gallons) is: 3100


From a barrel of crude oil, in one day, factory  𝐴  can produce

20 gallons of motor oil,
10 gallons of diesel oil, and
5 gallons of gasoline
Similarly, factory  𝐵  can produce

4 gallons of motor oil,
14 gallons of diesel oil, and
5 gallons of gasoline
while factory  𝐶  can produce

4 gallons of motor oil,
5 gallons of diesel oil, and
12 gallons of gasoline


Suppose the current daily demand from distributors is 6600 gallons of motor oil, 5100 gallons of diesel oil and 3100 of gasoline.

Set up the system of equations which describes the above situation.

### Buying another plant

####(Note the following given information. You will see questions in continuation to this, in the subsequent sections)

This situation has caused enough concern that the CEO is considering buying another plant, identical to the third, and using it permanently. Assuming that all 4 plants are on line, what production do you recommend to meet the current demand (5000, 8500, 10000)? In general, what can you say about any increased flexibility that the 4th plant might provide?

Let the number of barrels used by factory $A$, $B$, $C$ and $D$ are $x$, $y$, $z$ and $w$ respectively.

Then the system of linear equations will be

$$20x + 4y + 4z + 4w = 5000$$

$$10x + 14y + 5z + 5w = 8500$$

$$5x + 5y + 12z + 12w = 10000$$

The above system of linear equation has fewer equations than variables, hence it is *underdetermined* and cannot have a unique solution. In this case, there are either infinitely many solutions or no exact solution. We can solve it by keeping $w$ as constant and using [rref](http://linear.ups.edu/html/section-RREF.html) form to solve the system of linear equation.

To know about rref implementation in python refer [here](https://docs.sympy.org/latest/tutorial/matrices.html#rref).

In [29]:
import sympy as sy

# create symbol 'w'
w = sy.Symbol("w")
A_aug = sy.Matrix([[20, 4, 4, 5000-4*w],
                   [10, 14, 5, 8500-5*w],
                   [5, 5, 12, 10000-12*w]])
# show rref form
A_aug.rref()

(Matrix([
 [1, 0, 0,   195/4],
 [0, 1, 0,  1325/4],
 [0, 0, 1, 675 - w]]),
 (0, 1, 2))

From the above result, it can be seen that 4th plant will share the number of barrels required by the 3rd plant only, while the requirement of 1st and 2nd plant will remain unaffected.

### Calculate the amount of Paraffin supplied (1 point)

The company has just found a candle company that will buy its paraffin. Under the current conditions (i.e, after buying another plant) for demand (5000, 8500, 10000), how much can be supplied to them per day?

According to the problem statement, factory $A$ has 3 gallons of paraffin to dispose of per barrel of crude oil, factory $B$ 5 gallons, and factory $C$ 2 gallons.

In [31]:
from os import pardir
# YOUR CODE HERE
# A = 3 gallons of parrafin
# B = 5 gallons of parrafin
# C = 2 gallons of parrafin




### Selling the first plant (1 point)

The management is also considering selling the first plant due to aging equipment and high workman's compensation costs for the state it is located in. They would like to know what this would do to their production capability. Specifically, they would like an example of a demand they could not meet with only plants 2 and 3, and also what effect having plant 4 has (recall it is identical to plant 3). They would also like an example of a demand that they could meet with just plants 2 and 3. Any general statements you could make here would be helpful.

Let the number of barrels used by factory $B$, $C$ and $D$ are $y$, $z$ and $w$ respectively.

When considering only plants 2 and 3, and demand (5000, 8500, 10000) then we have

$$4y + 4z = 5000$$

$$14y + 5z = 8500$$

$$5y + 12z = 10000$$

In [36]:
# YOUR CODE HERE
# We now have 4𝑦+4𝑧=5000; 14𝑦+5𝑧=8500; 5𝑦+12𝑧=10000
# with 2 variables and 3 equations, we consider only two equations and try to see how this works out.

#consider 4𝑦+4𝑧=5000; 14𝑦+5𝑧=8500;
# Create the augmented matrix
A = np.array([[4, 4], [14, 5]])
# A = np.array([[20, 4, 4], [10, 14, 5], [0, 0, 0]])
b = np.array([5000, 8500])

int_xyz = np.linalg.solve(A, b).round().astype(int)
# int_xyz = np.round(xyz).astype(int)
print("x, y after rounding off: ", int_xyz)


print(f"The number of barrels of crude oil plant B should get is: {int_xyz[0]}")
print(f"The number of barrels of crude oil plant C should get is: {int_xyz[1]}")

motoroil_output = 4*int_xyz[0] + 4*int_xyz[1]
dieseloil_output = 14*int_xyz[0] + 5*int_xyz[1]
gasoline_output = 5*int_xyz[0] + 12*int_xyz[1]
print(f"Motor oil production(in gallons) is: {motoroil_output}")
print(f"Diesel oil production(in gallons) is: {dieseloil_output}")
print(f"Gasoline production(in gallons) is: {gasoline_output}")

x, y after rounding off:  [ 250 1000]
The number of barrels of crude oil plant B should get is: 250
The number of barrels of crude oil plant C should get is: 1000
Motor oil production(in gallons) is: 5000
Diesel oil production(in gallons) is: 8500
Gasoline production(in gallons) is: 13250


**Conclusion:**

1) Motor oil and diesel oil demand is completely met.

2) Gasoline production is overshot by 32.5%

Taking 4th plant into consideration.
Let the number of barrels used by factory $B$, $C$ and $D$ are $y$, $z$ and $w$ respectively.

Then for demand (5000, 8500, 10000) the system of linear equations will be

$$4y + 4z + 4w = 5000$$

$$14y + 5z + 5w = 8500$$

$$5y + 12z + 12w = 10000$$

Solve it using rref form.

In [37]:
# YOUR CODE HERE
# Create the augmented matrix
A = np.array([[4, 4, 4], [14, 5, 5], [5, 12, 12]])
b = np.array([5000, 8500, 10000])

print(b)

# xyz = np.linalg.solve(A, b)
int_xyz = np.linalg.solve(A, b).round().astype(int)
# int_xyz = np.round(xyz).astype(int)
print("x, y,z after rounding off: ", int_xyz)

print("To meet the doubled demand of the products:")
print(f"The number of barrels of crude oil plant B should get is: {int_xyz[0]}")
print(f"The number of barrels of crude oil plant C should get is: {int_xyz[1]}")
print(f"The number of barrels of crude oil plant D should get is: {int_xyz[2]}")


[ 5000  8500 10000]
x, y,z after rounding off:  [                 293 -1842381665742475520  1842381665742476288]
To meet the doubled demand of the products:
The number of barrels of crude oil plant B should get is: 293
The number of barrels of crude oil plant C should get is: -1842381665742475520
The number of barrels of crude oil plant D should get is: 1842381665742476288


Now, changing demand to (6600, 5100, 3100) and solving the system of equation using rref form.

In [ ]:
# YOUR CODE HERE

### Set rates for Products (1 point)

Company wants to set the rates of motor oil, diesel oil, and gasoline. For this purpose they have few suggestions given as follows:

* 100, 66, 102 Rupees per gallon,

* 104, 64, 100 Rupees per gallon,

* 102, 68, 98 Rupees per gallon, and

* 96, 68, 100 Rupees per gallon

for motor oil, diesel oil, and gasoline respectively.

Using matrix multiplication, find the rates which result in maximum total price.

Let $M$ denote the matrix such that rows represents different plants (A, B and C), columns represents different products (motor oil, diesel oil and gasoline) and each value represents production of that product from one barrel of crude oil for that plant.

$$M = \begin{bmatrix}
20 & 10 & 5 \\
4 & 14 & 5  \\
 4 & 5 & 12  
\end{bmatrix}$$

Also, $R$ is a matrix having different rates as its columns.

$$R = \begin{bmatrix}
100 & 104 & 102 & 96 \\
66 & 64 & 68 & 68  \\
102 & 100 & 98 & 100  
\end{bmatrix}$$

In [ ]:
# YOUR CODE HERE

### Marginal Cost (1 point)

The total cost $C(x)$ in Rupees, associated with the production of $x$ gallons of gasoline is given by

$$C(x) = 0.005 x^3 – 0.02 x^2 + 30x + 5000$$

Find the marginal cost when $22$ gallons are produced, where, marginal cost means the instantaneous rate of change of total cost at any level of output.

In [ ]:
# YOUR CODE HERE

### Marginal Revenue (1 point)

The total revenue in Rupees received from the sale of $x$ gallons of a motor oil is given by $$R(x) = 3x^2 + 36x + 5.$$

Find the marginal revenue, when $x = 28$, where, marginal revenue means the rate of change of total revenue with respect to the number of items sold at an instant.

In [ ]:
# YOUR CODE HERE

### Pouring crude oil in tank (1 point)

In a cylindrical tank of radius 10 meter, crude oil is being poured at the rate of 314 cubic meter per hour. Then find

* the rate at which the height of crude oil is increasing in the tank, and
* the height of crude oil in tank after 2 hours.

In [ ]:
# YOUR CODE HERE